// ============================================================================
// Student Types & Interfaces
// ============================================================================

import type { GenderValue, BloodGroupValue } from '@/constants/form-enums';
import type { AddressTypeValue } from '@/constants/address-type';

// Class Master (Grade Level)
export interface ClassMaster {
  id: number;
  name: string;
  code: string;
  display_order: number;
}

// Class Teacher
export interface ClassTeacher {
  public_id: string;
  full_name: string;
  email: string;
}

// Class Info (Section)
export interface ClassInfo {
  public_id: string;
  class_master: ClassMaster;
  name: string;
  class_teacher: ClassTeacher | null;
  capacity: number;
  student_count: number;
  is_full: boolean;
}

// Supervisor Info
export interface SupervisorInfo {
  email: string;
  full_name: string;
}

// Address Info (from backend)
export interface Address {
  id?: number;
  address_type: AddressTypeValue;
  street_address: string;
  address_line_2?: string;
  city: string;
  state: string;
  zip_code: string;
  country: string;
}

// User Info
export interface StudentUserInfo {
  public_id: string;
  username: string;
  first_name: string;
  last_name: string;
  full_name: string;
  email: string;
  phone: string;
  gender: GenderValue | '';
  blood_group?: BloodGroupValue;
  date_of_birth?: string;
  organization_role: string;
  supervisor: SupervisorInfo | null;
  address?: Address;
  is_active: boolean;
  is_email_verified: boolean;
}

// Student (Full Detail Response)
export interface Student {
  public_id: string;
  user_info: StudentUserInfo;
  class_info: ClassInfo;
  full_name: string;
  roll_number: string;
  admission_number: string;
  admission_date: string;
  guardian_name?: string;
  guardian_phone?: string;
  guardian_email?: string;
  guardian_relationship?: string;
  medical_conditions?: string;
  description?: string;
  previous_school_name?: string;
  previous_school_address?: string;
  previous_school_class?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  created_at: string;
  updated_at: string;
  created_by_public_id: string;
  created_by_name: string;
}

// Student List Item (Condensed for list views)
export interface StudentListItem {
  public_id: string;
  full_name: string;
  roll_number: string;
  admission_number: string;
  email?: string;
  phone?: string;
  class_name: string;
  class_id: string;
  class_master_name: string;
  gender: GenderValue | '';
  is_active: boolean;
}

// User Payload for Create
export interface StudentUserPayload {
  username?: string; // Optional - auto-generated by backend if not provided
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  role: 'student';
  gender?: GenderValue | '';
  blood_group?: BloodGroupValue;
  date_of_birth?: string;
  organization_role_code: 'STUDENT';
  supervisor_email?: string;
  address?: Address;
}

// Student Create Payload
export interface CreateStudentPayload {
  user: StudentUserPayload;
  roll_number: string;
  admission_number?: string;
  admission_date?: string;
  guardian_name?: string;
  guardian_phone?: string;
  guardian_email?: string;
  guardian_relationship?: string;
  medical_conditions?: string;
  description?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  previous_school_name?: string;
  previous_school_address?: string;
  previous_school_class?: string;
}

// Student Update Payload
export interface UpdateStudentPayload {
  user?: {
    first_name?: string;
    last_name?: string;
    email?: string;
    phone?: string;
    gender?: GenderValue | '';
    blood_group?: BloodGroupValue;
    date_of_birth?: string;
    address?: Partial<Address>;
  };
  roll_number?: string;
  admission_number?: string;
  admission_date?: string;
  guardian_name?: string;
  guardian_phone?: string;
  guardian_email?: string;
  guardian_relationship?: string;
  medical_conditions?: string;
  description?: string;
  emergency_contact_name?: string;
  emergency_contact_phone?: string;
  previous_school_name?: string;
  previous_school_address?: string;
  previous_school_class?: string;
}

// Query Parameters for List
export interface StudentQueryParams {
  page?: number;
  page_size?: number;
  search?: string;
  class_master_id?: string;
  class_assigned__public_id?: string;
  user__public_id?: string;
  is_deleted?: boolean;
  ordering?: string;
  for_attendance?: boolean;
}

// Bulk Upload
export interface BulkUploadStudentsPayload {
  file: File;
  class_id: string;
}

export interface BulkUploadResult {
  success: boolean;
  message: string;
  created_count: number;
  failed_count: number;
  errors?: Array<{
    row: number;
    errors: Record<string, string[]>;
  }>;
}

// Export
export interface ExportStudentsPayload {
  class_id?: string;
  email_addresses?: string[];
}

export interface ExportStudentsResult {
  success: boolean;
  message: string;
  file_url?: string;
}
